name: Обновление списков

on:
  schedule:
    - cron: '25 1 * * *'
  workflow_dispatch:

jobs:
  Update_lists:
    runs-on: ubuntu-latest
    
    steps:
    - name: Чекаем репо
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Скачиваем и обрабатываем список доменов для adlist.dat
      run: |
        mkdir -p data
        echo "Скачиваем актуальный список Hagezi Pro..."
        curl -sSLf https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro-onlydomains.txt -o temp.txt
        echo "Чистим комментарии из Hagezi Pro..."
        grep -v '^#' temp.txt > data/hagezi-pro-original
        echo "Проверяем наличие ad-filter/ignore.list..."
        if [[ -s "ad-filter/ignore.list" ]]; then # Проверяем, что ignore.list существует и не пустой
          echo "Найден ad-filter/ignore.list. Фильтруем hagezi-pro..."
          grep -v -x -f ad-filter/ignore.list data/hagezi-pro-original > data/hagezi-pro
          echo "Количество строк до фильтрации в hagezi-pro-original: $(wc -l < data/hagezi-pro-original)"
          echo "Количество строк после фильтрации в hagezi-pro: $(wc -l < data/hagezi-pro)"
        else
          echo "Файл ad-filter/ignore.list не найден, пуст или недоступен. Фильтрация hagezi-pro пропущена."
          cp data/hagezi-pro-original data/hagezi-pro
        fi
        echo "Очистка временных файлов..."
        rm temp.txt data/hagezi-pro-original
        echo "hagezi-pro contents (first 5 lines after potential filtering):"
        head -n 5 data/hagezi-pro || echo "Файл data/hagezi-pro не создан или пуст!"

    - name: Скачиваем и обрабатываем список доменов для adlist.json
      run: |
        echo "Скачиваем список для adlist.json..."
        curl -sSLf https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro-onlydomains.txt -o temp_domains.txt
        echo "Чистим комментарии из списка для adlist.json..."
        grep -v '^#' temp_domains.txt > filtered_domains_original.txt
        echo "Проверяем наличие ad-filter/ignore.list..."
        if [[ -s "ad-filter/ignore.list" ]]; then # Проверяем, что ignore.list существует и не пустой
          echo "Найден ad-filter/ignore.list. Фильтруем список для adlist.json..."
          grep -v -x -f ad-filter/ignore.list filtered_domains_original.txt > filtered_domains.txt
          echo "Количество строк до фильтрации в filtered_domains_original.txt: $(wc -l < filtered_domains_original.txt)"
          echo "Количество строк после фильтрации в filtered_domains.txt: $(wc -l < filtered_domains.txt)"
        else
          echo "Файл ad-filter/ignore.list не найден, пуст или недоступен. Фильтрация для adlist.json пропущена."
          cp filtered_domains_original.txt filtered_domains.txt
        fi
        echo "Проверяем отфильтрованные домены (filtered_domains.txt):"
        head -n 5 filtered_domains.txt || echo "Нет отфильтрованных доменов в filtered_domains.txt!"
        echo "Кол-во строк в filtered_domains.txt:"
        wc -l filtered_domains.txt
        echo "Создаем adlist.json..."
        jq -n --arg version "2" --argjson rules '[{"domain_suffix": []}]' \
          '{version: $version | tonumber, rules: $rules}' > adlist.json
        echo "Добавляем домены в adlist.json..."
        if [[ -s "filtered_domains.txt" ]]; then 
            jq --slurpfile domains <(grep -vE "^\s*$" filtered_domains.txt | jq -R -s 'split("\n") | map(select(length > 0))') \
              '.rules[0].domain_suffix = $domains[0]' adlist.json > temp_adlist.json && mv temp_adlist.json adlist.json
        else
            echo "Файл filtered_domains.txt пуст, в adlist.json не добавлены домены."
        fi
        echo "Очистка временных файлов..."
        rm temp_domains.txt filtered_domains_original.txt filtered_domains.txt
        echo "adlist.json содержит (первые 1000 символов):"
        head -c 1000 adlist.json || echo "adlist.json не создан или пуст!"

    - name: Устанавливаем GO
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Загружаем зависимости GO
      run: go mod download

    - name: Компилируем adlist.dat
      run: |
        go run ./ 
        echo "Ищем adlist.dat в root:"
        ls -la adlist.dat || echo "adlist.dat не найден в root"

    - name: Устанавливаем Sing-Box
      run: |
        echo "Установка Sing-Box..."
        bash <(curl -fsSL https://sing-box.app/deb-install.sh)
        
    - name: Компилируем adlist.srs
      run: |
        echo "Компилируем adlist.json в adlist.srs..."
        sing-box rule-set compile adlist.json 
        echo "Проверяем размер adlist.srs :"
        ls -lh adlist.srs || echo "adlist.srs не создан!"

    - name: Ставим дату релиза
      id: set-date
      run: echo "RELEASE_DATE=$(date +%d.%m.%Y)" >> $GITHUB_ENV

    - name: Создаем релиз
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "daily-release-${{ env.RELEASE_DATE }}"
        name: "Ежедневный выпуск ${{ env.RELEASE_DATE }}"
        files: |
          adlist.dat
          adlist.srs
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Удаляем старые релизы
      uses: dev-drprasad/delete-older-releases@v0.3.4
      with:
        keep_latest: 6
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Удаляем старые workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
        repository: ${{ github.repository }}
        delete_workflow_pattern: update.yml
        retain_days: 7
        keep_minimum_runs: 0
